Changed null to undefined for sourceFileName and sourceMapTarget.
Babel 7 returns errors for sourceFileName and sourceMapTarget because they are specified as null.
Error: .sourceFileName must be a string, or undefined